package com.sunit.navimenu.po; 
 
 
 
 
 
 
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;

import com.sunit.relations.action.RelationsAction;
import com.sunit.relations.capability.AbstractRelationsAbility;
import com.sunit.sysmanager.po.SysResource;

/**
 * Navimenu generated by hbm2java
 */
@Entity
@Table(name="tb_navimenu"
  //  ,catalog="scm" 
)

@gen.SLH("eyJmb3JtSW5wdXRUeXBlIjoiRElWIiwiZ3JpZExpc3QiOiJ0aXRsZSxzeXNyZXNvdXJjZV9pZCxyZW1hcmsiLCJ3aWR0aCI6Ijg2MiIsImNvZGUiOiJ0Yl9uYXZpbWVudSIsInNsaE5hbWUiOiKyy7Wlse0iLCJmb3JtTGF5b3V0IjoiMywxLDEsMSJ9")    
public class Navimenu extends   AbstractRelationsAbility<Navimenu>   implements java.io.Serializable {
 

			    @gen.SLH("eyJmb3JtSW5wdXRUeXBlIjoidGV4dCIsImdyaWRJc0hpZGUiOiJ0cnVlIiwid2lkdGgiOiIyNzEiLCJkYkxlbmd0aCI6IjEwMCIsImV4Y2x1ZGUiOiJ0cnVlIiwiY29kZSI6ImNyZWF0b3IiLCJzbGhOYW1lIjoitLS9qNXfIn0=")     
	 private String creator;
	
			    @gen.SLH("eyJmb3JtSW5wdXRUeXBlIjoidGV4dCIsImdyaWRJc0hpZGUiOiJ0cnVlIiwid2lkdGgiOiIyNzEiLCJkYkxlbmd0aCI6IjEwMCIsImV4Y2x1ZGUiOiJ0cnVlIiwiY29kZSI6ImNyZWF0b3Jfb3JnIiwic2xoTmFtZSI6IrS0vajV39fp1q8ifQ==")     
	 private String creatorOrg;
	
			    @gen.SLH("eyJmb3JtSW5wdXRUeXBlIjoiZGF0ZSIsImdyaWRJc0hpZGUiOiJ0cnVlIiwid2lkdGgiOiIyNzEiLCJkYkxlbmd0aCI6IjEwMCIsImV4Y2x1ZGUiOiJ0cnVlIiwiY29kZSI6ImNyZWF0ZV90aW1lIiwic2xoTmFtZSI6IrS0vajKsbzkIn0=")     
	 private String createTime;
	
			    @gen.SLH("eyJmb3JtSW5wdXRUeXBlIjoidGV4dCIsImxpc3RTZWFyY2giOnsib3BlcmF0b3IiOiJsaWtlIiwib3BlcmF0b3JGaWVsZCI6InRpdGxlIn0sImZvcm1WYWxpZGF0ZSI6IiAgIGxldHRlck51bWJlckNoaW5lc2UgPScxJyIsIndpZHRoIjoiMjcxIiwiZGJMZW5ndGgiOiIxMDAiLCJjb2RlIjoidGl0bGUiLCJzbGhOYW1lIjoissu1pcP7s8YifQ==")     
	 private String title;
	
			    @gen.SLH("eyJwc3VpYXJncyI6eyJkZWZhdWx0T3B0aW9uIjpbeyJpZCI6IiIsInZhbHVlIjoix+vRodTxIn1dLCJkYXRhVXJsIjoiL3N5c3Jlc291cmNlL2dldFBhcmVudFN5c291clNlbElkLmFjdGlvbiIsImpzb25SZWFkZXIiOnsiaWQiOiJpZCIsInZhbHVlIjoibmFtZSJ9fSwiZm9ybUlucHV0VHlwZSI6InN1aXNlbGVjdCIsIndpZHRoIjoiMTgzIiwiZGJMZW5ndGgiOiIzMiIsImNvZGUiOiJzeXNyZXNvdXJjZV9pZCIsInNsaE5hbWUiOiK21NOm18rUtCJ9")     
	 private String sysresourceId;
	
			    @gen.SLH("eyJmb3JtSW5wdXRUeXBlIjoiVEVYVEFSRUEiLCJ3aWR0aCI6IjI1OSIsImRiTGVuZ3RoIjoiMjAwIiwiY29kZSI6InJlbWFyayIsInNsaE5hbWUiOiJyZW1hcmsifQ==")     
	 private String remark;
	
    
    
    private SysResource  sysResource;
    
 
    
    

    public Navimenu() {
    }

	
    public Navimenu(String id) {
        this.id = id;
    }
    public Navimenu(String id, String creator, String creatorOrg, String createTime, String title, String sysresourceId, String remark) {
       this.id = id;
       this.creator = creator;
       this.creatorOrg = creatorOrg;
       this.createTime = createTime;
       this.title = title;
       this.sysresourceId = sysresourceId;
       this.remark = remark;
    }
   

    
    @Column(name="creator", length=100)
	    public String getCreator() {
	        return this.creator;
	    }
	    
	    public void setCreator(String creator) {
	        this.creator = creator;
	    }

    
    @Column(name="creator_org", length=100)
	    public String getCreatorOrg() {
	        return this.creatorOrg;
	    }
	    
	    public void setCreatorOrg(String creatorOrg) {
	        this.creatorOrg = creatorOrg;
	    }

    
    @Column(name="create_time", length=100)
	    public String getCreateTime() {
	        return this.createTime;
	    }
	    
	    public void setCreateTime(String createTime) {
	        this.createTime = createTime;
	    }

    
    @Column(name="title", length=100)
	    public String getTitle() {
	        return this.title;
	    }
	    
	    public void setTitle(String title) {
	        this.title = title;
	    }

    
    @Column(name="sysresource_id", length=32)
	    public String getSysresourceId() {
	        return this.sysresourceId;
	    }
	    
	    public void setSysresourceId(String sysresourceId) {
	        this.sysresourceId = sysresourceId;
	    }

    
    @Column(name="remark", length=200)
	    public String getRemark() {
	        return this.remark;
	    }
	    
	    public void setRemark(String remark) {
	        this.remark = remark;
	    }


		@Transient
		
		@OneToOne()
		@JoinColumn(name="sysresource_id")
		public SysResource getSysResource() {
			return sysResource;
		}


		public void setSysResource(SysResource sysResource) {
			this.sysResource = sysResource;
		}




}


  