package com.sunit.relations.po; 
 
 
 
 
 
 
 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Relations generated by hbm2java
 */
@Entity
@Table(name="tb_relation_tree"
   
)  

@gen.SLH("{'formInputType':'DIV','width':'1164','code':'tb_relations','slhName':'用户关系树表'}")    
public class RelationTree extends com.sunit.global.base.AbstractID implements java.io.Serializable { 


			    @gen.SLH("{'formInputType':'text','formValidate':'','width':'300','dbLength':'10','code':'relations_left','dbType':'int','slhName':'节点起点'}")     
	 private Integer relationsLeft;
	
			    @gen.SLH("{'psuiargs':'#{defaultOption:[{id:'',value:'请选择'}],dataUrl:'/user/getSelectBody.action',jsonReader:{'id':'id','value':'userName'}}#','formInputType':'suiselect','listSearch':'#{operator:'=',operatorField:'userName',operatorObject:'User' }#','width':'300','dbLength':'32','code':'relations_userId','slhName':'userId'}")     
	 private String relationsUserId;
	
			    @gen.SLH("{'psuiargs':'#{defaultOption:[{id:'',value:'请选择'}],dataUrl:'/user/getSelectBody.action',jsonReader:{'id':'id','value':'userName'}}#','formInputType':'suiselect','listSearch':'#{operator:'=',operatorField:'userName',operatorObject:'User' }#','width':'300','dbLength':'32','code':'relations_ancestorId','slhName':'祖先Id'}")     
	 private String relationsAncestorId;
	
			    @gen.SLH("{'formInputType':'text','formValidate':'','width':'300','dbLength':'10','code':'relations_right','dbType':'int','slhName':'节点终点'}")     
	 private Integer relationsRight;
	
			    @gen.SLH("{'formInputType':'text','width':'300','dbLength':'10','code':'relations_level','dbType':'int','slhName':'所在层次'}")     
	 private Integer relationsLevel;
	
			    @gen.SLH("{'psuiargs':'#{defaultOption:[{id:'',value:'请选择'}],dataUrl:'/user/getSelectBody.action',jsonReader:{'id':'id','value':'userName'}}#','formInputType':'suiselect','listSearch':'#{operator:'=',operatorField:'userName',operatorObject:'User' }#','width':'300','dbLength':'32','code':'relations_parentId','slhName':'parentId'}")     
	 private String relationsParentId;
	
			    @gen.SLH("{'formInputType':'text','width':'300','dbLength':'500','code':'remark','slhName':'remark'}")     
	 private String remark;
			    
	 private String className;
	 
	 private String classId;
	 
	

    public RelationTree() {
    }

	
    public RelationTree(String id) {
        this.id = id;
    }
    public RelationTree(String id, Integer relationsLeft, String relationsUserId, String relationsAncestorId, Integer relationsRight, Integer relationsLevel, String relationsParentId, String remark) {
       this.id = id;
       this.relationsLeft = relationsLeft;
       this.relationsUserId = relationsUserId;
       this.relationsAncestorId = relationsAncestorId;
       this.relationsRight = relationsRight;
       this.relationsLevel = relationsLevel;
       this.relationsParentId = relationsParentId;
       this.remark = remark;
    }
   

    
    @Column(name="relations_left")
	    public Integer getRelationsLeft() {
	        return this.relationsLeft;
	    }
	    
	    public void setRelationsLeft(Integer relationsLeft) {
	        this.relationsLeft = relationsLeft;
	    }

    
    @Column(name="relations_userId", length=32)
	    public String getRelationsUserId() {
	        return this.relationsUserId;
	    }
	    
	    public void setRelationsUserId(String relationsUserId) {
	        this.relationsUserId = relationsUserId;
	    }

    
    @Column(name="relations_ancestorId", length=32)
	    public String getRelationsAncestorId() {
	        return this.relationsAncestorId;
	    }
	    
	    public void setRelationsAncestorId(String relationsAncestorId) {
	        this.relationsAncestorId = relationsAncestorId;
	    }

    
    @Column(name="relations_right")
	    public Integer getRelationsRight() {
	        return this.relationsRight;
	    }
	    
	    public void setRelationsRight(Integer relationsRight) {
	        this.relationsRight = relationsRight;
	    }

    
    @Column(name="relations_level")
	    public Integer getRelationsLevel() {
	        return this.relationsLevel;
	    }
	    
	    public void setRelationsLevel(Integer relationsLevel) {
	        this.relationsLevel = relationsLevel;
	    }

    
    @Column(name="relations_parentId", length=32)
	    public String getRelationsParentId() {
	        return this.relationsParentId;
	    }
	    
	    public void setRelationsParentId(String relationsParentId) {
	        this.relationsParentId = relationsParentId;
	    }

    
    @Column(name="remark")
	    public String getRemark() {
	        return this.remark;
	    }
	    
	    public void setRemark(String remark) {
	        this.remark = remark;
	    }

	    @Column(name="class_name", length=300)
		public String getClassName() {
			return className;
		}


		public void setClassName(String className) {
			this.className = className;
		}

		 @Column(name="class_id",nullable=false)
		public String getClassId() {
			return classId;
		}


		public void setClassId(String classId) {
			this.classId = classId;
		}




}


  